whitelist_rules:
  - closure_spacing
  - colon
  - empty_enum_arguments
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - operator_usage_whitespace
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - trailing_newline
  - type_name
  - unused_closure_parameter
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - custom_rules
  - fatal_error_message
  - implicitly_unwrapped_optional
  - trailing_whitespace
  - force_try
  - force_cast
  - force_unwrapping

excluded:
  - Audio
  - Carthage
  - Pods
  - script

variable_name:
  excluded:
    - id
    - URL

line_length: 256

indentation: 4

type_name:
  excluded:
    - OPass

force_try:
  severity: warning

force_cast:
  severity: warning

force_unwrapping:
  severity: warning

unused_closure_parameter:
  severity: warning

closure_spacing:
  severity: error

empty_enum_arguments:
  severity: error

legacy_cggeometry_functions:
  severity: error

legacy_constant:
  severity: error

legacy_constructor:
  severity: error

legacy_nsgeometry_functions:
  severity: error

operator_usage_whitespace:
  severity: error

redundant_string_enum_value:
  severity: error

redundant_void_return:
  severity: error

return_arrow_whitespace:
  severity: error

trailing_newline:
  severity: error

unused_optional_binding:
  severity: error

vertical_whitespace:
  severity: error

trailing_whitespace:
  severity: error

void_return:
  severity: error

fatal_error_message:
  severity: error
