plugin 'cocoapods-acknowledgements'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'CCIP' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for CCIP
  pod 'OneSignal'
  pod 'UICKeyChainStore', '~> 2.1'
  pod 'Google/Analytics'
  pod 'ICViewPager', :git => 'https://github.com/FrankWu100/ICViewPager'
  pod 'STPopup', '~> 1.7'
  pod 'ColorArt', '0.1.1'
  pod 'iRate', '~> 1.11'
  pod 'iCarousel', '~> 1.8'
  pod 'BLKFlexibleHeightBar'
  pod 'SDWebImage', '~>3.8'
  pod 'Shimmer', '~>1.0'
  pod 'MMMarkdown', '~> 0.5'
  pod 'CPDAcknowledgements', '~> 1.0'
end
