# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'CCIP' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for CCIP
  pod 'OneSignal'
  pod 'UICKeyChainStore', '~> 2.1'
  pod 'Google/Analytics'
  pod 'ICViewPager', :git => 'https://github.com/FrankWu100/ICViewPager'
  pod 'STPopup', '~> 1.7'
end
