plugin 'cocoapods-acknowledgements'

# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

def ccip_pods
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    
    # Pods for CCIP
    pod 'OneSignal', '~> 1.13'
    pod 'UICKeyChainStore', '~> 2.1'
    pod 'Google/Analytics', '~> 3.0.3'
    pod 'ICViewPager', :git => 'https://github.com/FrankWu100/ICViewPager'
    pod 'STPopup', '~> 1.7'
    pod 'ColorArt', '0.1.1'
    pod 'iRate', '~> 1.11'
    pod 'iCarousel', '~> 1.8'
    pod 'BLKFlexibleHeightBar', '~> 1.0'
    pod 'SDWebImage', '~>3.8'
    pod 'Shimmer', '~>1.0'
    pod 'MMMarkdown', '~> 0.5'
    pod 'CPDAcknowledgements', '~> 1.0'
    pod 'NJKWebViewProgress', '~> 0.2'
    pod 'iVersion', '~> 1.11'
    pod 'AFNetworking', '~> 3.1'
    pod 'UITableView+FDTemplateLayoutCell', :git => 'https://github.com/Haraguroicha/UITableView-FDTemplateLayoutCell', :tag => '1.6.1'
    pod 'UIView+FDCollapsibleConstraints', '~> 1.1'
    pod 'EFQRCode', '~> 1.2.7'
    pod 'MWPhotoBrowser', '~> 2.1.2'
    pod 'MBProgressHUD', '~> 0.9.2'
end

target 'COSCUP' do
    ccip_pods
end

target 'SITCON' do
    ccip_pods
end
